### ISSUE TITLE
Internal error on Enso IDE on Windows

### ISSUE THREAD

**Issue by joenash** [enso-org/ide#1107]
Using this version, sent to be by Sylwia to test: https://github.com/enso-org/ide/actions/runs/479698279

### General Summary
On start, the Enso IDE crashes with the following error:
![enso-windows-1](https://user-images.githubusercontent.com/1790822/104313927-06950d00-54d9-11eb-95f5-cfcde3203b12.png)
Shortly after, it crashes again:
![enso-windows-2](https://user-images.githubusercontent.com/1790822/104313953-0c8aee00-54d9-11eb-9142-054e11db61f7.png)
Report fails:
![enso-windows-3](https://user-images.githubusercontent.com/1790822/104313968-101e7500-54d9-11eb-9397-c082b8cf840b.png)

### Steps to Reproduce
Downloaded from the above linked action, installed on Windows 10 Home 19041.685

**Comment by wdanilo** [comment]
@joenash Please run this not by double click, but fro CMD with `--dev` option and tell us what you see in the console there.

**Comment by joenash** [comment]
@wdanilo nothing relevant in the terminal output (which I gather is expected), this is from the inspector console: 



```﻿
DevTools failed to load SourceMap: Could not parse content for http://localhost:8080/scala-parser.js.map: Unexpected token < in JSON at position 0
electron/js2c/renderer_init.js:91 Unable to load preload script: C:\Users\joenash\AppData\Local\Programs\Enso\resources\app.asar\preload.js
electron/js2c/renderer_init.js:91 TypeError: Cannot read property 'getCurrentWindow' of undefined
    at Object.<anonymous> (C:\Users\joenash\App…p.asar\preload.js:1)
    at Object.<anonymous> (C:\Users\joenash\App….asar\preload.js:40)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Object.<anonymous> (electron/js2c/renderer_init.js:91)
    at Object../lib/renderer/init.ts (electron/js2c/renderer_init.js:91)
    at __webpack_require__ (electron/js2c/renderer_init.js:3)
DevTools failed to load SourceMap: Could not parse content for http://localhost:8080/scala-parser.js.map: Unexpected token < in JSON at position 0
VM184:2739 Uncaught RustPanic: panicked at 'Failed to setup project model.: RemoteError(Error { code: 4012, message: "Error parsing extra fields for entry: enso-0.2.0/ - Type `org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.", data: None })', src/libcore/result.rs:1165:5
    at new_panic_error (eval at <anonymous> (http://localhost:8080/assets/index.js:171:28), <anonymous>:2745:12)
    at imports.wbg.__wbg_newpanicerror_9abe88c725084077 (eval at <anonymous> (http://localhost:8080/assets/index.js:171:28), <anonymous>:806:140)
    at ensogl_system_web::new_panic_error::ha95030de5c8c0efe (http://localhost:8080/assets/ide.wasm:wasm-function[14139]:0xa2cc7c)
    at ensogl_system_web::error_throwing_panic_hook::ha0f5cf816b6835ad (http://localhost:8080/assets/ide.wasm:wasm-function[17441]:0xa704a9)
    at core::ops::function::Fn::call::h4c5b5525a3559f51 (http://localhost:8080/assets/ide.wasm:wasm-function[20015]:0xa7a4d7)
    at std::panicking::rust_panic_with_hook::h47eeb283bb214998 (http://localhost:8080/assets/ide.wasm:wasm-function[11154]:0x99adf6)
    at std::panicking::continue_panic_fmt::h39bbc58bc08cdcf3 (http://localhost:8080/assets/ide.wasm:wasm-function[14642]:0xa3b569)
    at rust_begin_unwind (http://localhost:8080/assets/ide.wasm:wasm-function[20071]:0xa7a71c)
    at core::panicking::panic_fmt::h29e139592fa77d11 (http://localhost:8080/assets/ide.wasm:wasm-function[16953]:0xa6b70d)
    at core::result::unwrap_failed::h21a38615bdc61c62 (http://localhost:8080/assets/ide.wasm:wasm-function[14111]:0xa2befa)
    at ide::ide::initializer::Initializer::start_and_forget::{{closure}}::he7220f615eb21843 (http://localhost:8080/assets/ide.wasm:wasm-function[283]:0x645b8)
    at <std::future::GenFuture<T> as core::future::future::Future>::poll::h9bca1e815f964040 (http://localhost:8080/assets/ide.wasm:wasm-function[15298]:0xa4cb6a)
    at futures_util::stream::stream::StreamExt::poll_next_unpin::hba4ce4c9872a16e5 (http://localhost:8080/assets/ide.wasm:wasm-function[2091]:0x4c3c82)
    at futures_executor::local_pool::LocalPool::poll_pool_once::h1925319d88bb91e8 (http://localhost:8080/assets/ide.wasm:wasm-function[10199]:0x95702e)
    at std::thread::local::LocalKey<T>::with::h4c2a44f825169b89 (http://localhost:8080/assets/ide.wasm:wasm-function[10991]:0x98fe31)
    at futures_executor::local_pool::LocalPool::run_until_stalled::hb19f5bc9afbb2fd2 (http://localhost:8080/assets/ide.wasm:wasm-function[13201]:0xa08516)
    at <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut::h49a11c9102fc6442 (http://localhost:8080/assets/ide.wasm:wasm-function[15386]:0xa4ebe0)
    at <core::option::Option<T> as enso_prelude::option::OptionOps>::for_each::h4597d8c2e90f7128 (http://localhost:8080/assets/ide.wasm:wasm-function[4776]:0x707758)
    at <ensogl_core::animation::loops::DynamicLoop as core::default::Default>::default::{{closure}}::hf89673bb5a768d9d (http://localhost:8080/assets/ide.wasm:wasm-function[15709]:0xa55b12)
    at ensogl_core::animation::loops::RawLoop<Callback>::new::{{closure}}::h5649eac9ec0bf022 (http://localhost:8080/assets/ide.wasm:wasm-function[10253]:0x95b294)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h995b8cbc0d0b20fc (http://localhost:8080/assets/ide.wasm:wasm-function[17288]:0xa6ef78)
    at __wbg_adapter_39 (eval at <anonymous> (http://localhost:8080/assets/index.js:171:28), <anonymous>:370:10)
    at real (eval at <anonymous> (http://localhost:8080/assets/index.js:171:28), <anonymous>:2148:24)```

**Comment by MichaelMauderer** [comment]
I can reproduce this on Win10.
Will try with a fresh local source build next.

**Comment by MichaelMauderer** [comment]
The actual root cause for this not working on Windows is this engine issue: https://github.com/enso-org/enso/issues/1371
Once this is resolved we should re-investigate this issue.
