### ISSUE TITLE
Errors in IDE dev console on start (Windows and Linux)

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#285]
### General Summary

There is a set of bugs when IDE package is starting
### Steps to Reproduce

download and run IDE package with `--dev` option
### Expected Result

clean dev console
### Actual Result

```
electron/js2c/renderer_init.js:2324 Unable to load preload script: C:\Users\Username\AppData\Local\Programs\enso-studio-client\resources\app.asar\preload.js
(anonymous) @ electron/js2c/renderer_init.js:2324
electron/js2c/renderer_init.js:2325 TypeError: win.setWindowButtonVisibility is not a function
    at Object.<anonymous> (C:\Users\Username\AppData\Local\Programs\enso-studio-client\resources\app.asar\preload.js:38:5)
    at Object.<anonymous> (C:\Users\Username\AppData\Local\Programs\enso-studio-client\resources\app.asar\preload.js:60:3)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (electron/js2c/renderer_init.js:2321:16)
    at Object../lib/renderer/init.ts (electron/js2c/renderer_init.js:2335:30)
```
### Enso Version

core     : 2.0.0-alpha.0
build    : 6793b78
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by joenash** [comment]
Just an fyi, a user asked about this error in Discord today: https://discord.com/channels/401396655599124480/403573875901726720/798563784066990100

My understanding from the label dance on this issue so far is that this error doesn't affect usage? We should flag it as a known problem for the list when we send out the build to testers @sylwiabr 

<blockquote><img src="https://discord.com/assets/ee7c382d9257652a88c8f7b7f22a994d.png" width="48" align="right"><div><img src="/assets/07dca80a102d4149e9736d4b162cff6f.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/403573875901726720/798563784066990100">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>

**Comment by sylwiabr** [comment]
Yes, it does not affect usage and we should put it to `known issues` @joenash

**Comment by sylwiabr** [comment]
It should be fixed with new Electron - please reopen this if it still occurs @farmaazon @MichaelMauderer
